# Generated by Django 4.2.4 on 2023-12-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_email', models.CharField(default='', max_length=70)),
                ('customer_phone', models.CharField(default='', max_length=11)),
                ('customer_query', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
